import { api } from "@/lib/api";
export type ApiParams = Record<string, string | number | boolean | undefined | null>;
export const assetflowService = {
  login: (email: string, password: string) => api.post("/auth/login", { email, password }),
  logout: () => api.post("/auth/logout"),
  me: () => api.get("/auth/me"),
  dashboard: () => api.get("/dashboard/stats"),
  masterOptions: (params?: ApiParams) => api.get("/master/options", { params }),

  companies: (params?: ApiParams) => api.get("/companies", { params }),
  company: (id: string) => api.get(`/companies/${id}`),
  createCompany: (payload: unknown) => api.post("/companies", payload),
  updateCompany: (id: string, payload: unknown) => api.patch(`/companies/${id}`, payload),
  deleteCompany: (id: string) => api.delete(`/companies/${id}`),

  roles: () => api.get("/users/roles"),
  createRole: (payload: unknown) => api.post("/users/roles", payload),
  updateRole: (id: string, payload: unknown) => api.patch(`/users/roles/${id}`, payload),
  deleteRole: (id: string) => api.delete(`/users/roles/${id}`),

  users: (params?: ApiParams) => api.get("/users", { params }),
  user: (id: string) => api.get(`/users/${id}`),
  createUser: (payload: unknown) => api.post("/users", payload),
  updateUser: (id: string, payload: unknown) => api.patch(`/users/${id}`, payload),

  categories: (params?: ApiParams) => api.get("/categories", { params }),
  category: (id: string) => api.get(`/categories/${id}`),
  createCategory: (payload: unknown) => api.post("/categories", payload),
  updateCategory: (id: string, payload: unknown) => api.patch(`/categories/${id}`, payload),
  deleteCategory: (id: string) => api.delete(`/categories/${id}`),
  categoryTemplateUrl: () => `${process.env.NEXT_PUBLIC_API_URL || "http://localhost:5000/api/v1"}/categories/template`,

  assets: (params?: ApiParams) => api.get("/assets", { params }),
  asset: (id: string) => api.get(`/assets/${id}`),
  createAsset: (payload: unknown) => api.post("/assets", payload),
  createAssetsBulk: (payload: unknown) => api.post("/assets/bulk", payload),
  importAssetsCsv: (csv: string) => api.post("/assets/import", { csv }),
  updateAsset: (id: string, payload: unknown) => api.patch(`/assets/${id}`, payload),
  deleteAsset: (id: string) => api.delete(`/assets/${id}`),
  assignAsset: (id: string, payload: unknown) => api.post(`/assets/${id}/assign`, payload),
  returnAsset: (id: string, payload: unknown) => api.post(`/assets/${id}/return`, payload),
  assetQr: (id: string) => api.get(`/assets/${id}/qr`),
  assetFinanceHistory: (id: string) => api.get(`/reports/assets/${id}/history`),
  assetFinanceHistoryPdfUrl: (id: string) => `${process.env.NEXT_PUBLIC_API_URL || "http://localhost:5000/api/v1"}/reports/assets/${id}/history/pdf`,
  assetTemplateUrl: () => `${process.env.NEXT_PUBLIC_API_URL || "http://localhost:5000/api/v1"}/assets/template`,

  employees: (params?: ApiParams) => api.get("/employees", { params }),
  employee: (id: string) => api.get(`/employees/${id}`),
  createEmployee: (payload: unknown) => api.post("/employees", payload),
  updateEmployee: (id: string, payload: unknown) => api.patch(`/employees/${id}`, payload),
  deleteEmployee: (id: string) => api.delete(`/employees/${id}`),

  vendors: (params?: ApiParams) => api.get("/vendors", { params }),
  vendor: (id: string) => api.get(`/vendors/${id}`),
  createVendor: (payload: unknown) => api.post("/vendors", payload),
  updateVendor: (id: string, payload: unknown) => api.patch(`/vendors/${id}`, payload),
  deleteVendor: (id: string) => api.delete(`/vendors/${id}`),

  purchases: (params?: ApiParams) => api.get("/purchases", { params }),
  purchase: (id: string) => api.get(`/purchases/${id}`),
  createPurchase: (payload: unknown) => api.post("/purchases", payload),
  updatePurchase: (id: string, payload: unknown) => api.patch(`/purchases/${id}`, payload),
  deletePurchase: (id: string) => api.delete(`/purchases/${id}`),
  purchasePdfUrl: (id: string) => `${process.env.NEXT_PUBLIC_API_URL || "http://localhost:5000/api/v1"}/purchases/${id}/pdf`,

  repairs: (params?: ApiParams) => api.get("/repairs", { params }),
  repair: (id: string) => api.get(`/repairs/${id}`),
  createRepair: (payload: unknown) => api.post("/repairs", payload),
  updateRepair: (id: string, payload: unknown) => api.patch(`/repairs/${id}`, payload),
  deleteRepair: (id: string) => api.delete(`/repairs/${id}`),
  repairPdfUrl: (id: string) => `${process.env.NEXT_PUBLIC_API_URL || "http://localhost:5000/api/v1"}/repairs/${id}/pdf`,

  assignments: (params?: ApiParams) => api.get("/assignments", { params }),
  assignment: (id: string) => api.get(`/assignments/${id}`),
  createAssignment: (payload: unknown) => api.post("/assignments", payload),
  updateAssignment: (id: string, payload: unknown) => api.patch(`/assignments/${id}`, payload),
  deleteAssignment: (id: string) => api.delete(`/assignments/${id}`),
  assignmentPdfUrl: (id: string) => `${process.env.NEXT_PUBLIC_API_URL || "http://localhost:5000/api/v1"}/assignments/${id}/pdf`,

  returns: (params?: ApiParams) => api.get("/returns", { params }),
  returnRecord: (id: string) => api.get(`/returns/${id}`),
  updateReturn: (id: string, payload: unknown) => api.patch(`/returns/${id}`, payload),
  deleteReturn: (id: string) => api.delete(`/returns/${id}`),
  returnPdfUrl: (id: string) => `${process.env.NEXT_PUBLIC_API_URL || "http://localhost:5000/api/v1"}/returns/${id}/pdf`,
  openEmployeeAssignments: (employeeId: string, params?: ApiParams) => api.get(`/returns/employee/${employeeId}/open`, { params }),
  createReturn: (payload: unknown) => api.post("/returns", payload),

  scannerSearch: (q: string) => api.get("/scanner/search", { params: { q } }),
  auditLogs: (params?: ApiParams) => api.get("/audit-logs", { params }),
  auditLog: (id: string) => api.get(`/audit-logs/${id}`),
  reportAssets: (params?: ApiParams) => api.get("/reports/assets", { params }),
  reportDepreciation: (params?: ApiParams) => api.get("/reports/depreciation", { params }),
  exportAssetsCsvUrl: () => `${process.env.NEXT_PUBLIC_API_URL || "http://localhost:5000/api/v1"}/exports/assets.csv`,
  exportAssetsPdfUrl: () => `${process.env.NEXT_PUBLIC_API_URL || "http://localhost:5000/api/v1"}/exports/assets.pdf`,
  exportEmployeesPdfUrl: () => `${process.env.NEXT_PUBLIC_API_URL || "http://localhost:5000/api/v1"}/exports/employees.pdf`,
  exportVendorsPdfUrl: () => `${process.env.NEXT_PUBLIC_API_URL || "http://localhost:5000/api/v1"}/exports/vendors.pdf`,
  exportPurchasesPdfUrl: () => `${process.env.NEXT_PUBLIC_API_URL || "http://localhost:5000/api/v1"}/exports/purchases.pdf`,
  exportAssignmentsPdfUrl: () => `${process.env.NEXT_PUBLIC_API_URL || "http://localhost:5000/api/v1"}/exports/assignments.pdf`,
  exportReturnsPdfUrl: () => `${process.env.NEXT_PUBLIC_API_URL || "http://localhost:5000/api/v1"}/exports/returns.pdf`,
  exportRepairsPdfUrl: () => `${process.env.NEXT_PUBLIC_API_URL || "http://localhost:5000/api/v1"}/exports/repairs.pdf`,
  exportFinancePdfUrl: () => `${process.env.NEXT_PUBLIC_API_URL || "http://localhost:5000/api/v1"}/exports/finance.pdf`,
};
