import { Router } from "express";
import { Asset, AssetAssignment, AssetCategory, AssetReturn, AuditLog, Company, Employee, Location, Purchase, RepairTicket, Vendor } from "../models";

export const exportRoutes = Router();

function csvEscape(v: unknown) {
  return `"${String(v ?? "").replace(/"/g, '""')}"`;
}

function safe(v: unknown) {
  return String(v ?? "-").replace(/[&<>"']/g, (ch) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" }[ch] || ch));
}

function reportHtml(title: string, columns: string[], rows: unknown[][], summary?: string) {
  const compact = columns.length > 8;
  return `<!doctype html><html><head><title>${safe(title)}</title><style>
  *{box-sizing:border-box}body{font-family:Arial,Helvetica,sans-serif;padding:28px;color:#0f172a;background:#fff}.brand{display:flex;align-items:flex-start;justify-content:space-between;border-bottom:3px solid #0f766e;padding-bottom:14px;margin-bottom:18px}.brand h1{margin:0;color:#0f766e;font-size:28px}.brand p{margin:4px 0 0;color:#64748b;font-size:12px}h2{margin:0 0 10px;font-size:20px}.summary{border:1px solid #cbd5e1;border-radius:14px;padding:12px 14px;margin:14px 0;background:#f8fafc;color:#334155;font-size:12px}table{width:100%;border-collapse:collapse;margin-top:12px}th{background:#f0fdfa;color:#115e59;font-weight:700}td,th{border:1px solid #cbd5e1;padding:${compact ? "6px" : "8px"};font-size:${compact ? "9.5px" : "11px"};text-align:left;vertical-align:top}tr:nth-child(even){background:#f8fafc}.footer{margin-top:18px;color:#64748b;font-size:11px}@page{size:A4 landscape;margin:12mm}@media print{button{display:none}body{padding:0}}
 </style></head><body><div class="brand"><div><h1>AssetFlow</h1><p>Enterprise Asset Management Suite</p></div><p>Generated ${new Date().toLocaleString()}</p></div><h2>${safe(title)}</h2>${summary ? `<div class="summary">${summary}</div>` : ""}<table><thead><tr>${columns.map((c) => `<th>${safe(c)}</th>`).join("")}</tr></thead><tbody>${rows.map((r) => `<tr>${r.map((c) => `<td>${safe(c)}</td>`).join("")}</tr>`).join("")}</tbody></table><div class="footer">This report is generated by AssetFlow. Use browser print/save as PDF for a final PDF copy.</div><script>window.print()</script></body></html>`;
}

function sendHtml(res: any, filename: string, html: string) {
  res.setHeader("Content-Type", "text/html; charset=utf-8");
  res.setHeader("Content-Disposition", `inline; filename=${filename}`);
  res.send(html);
}

exportRoutes.get("/assets.csv", async (_req, res, next) => {
  try {
    const rows = await Asset.findAll({ include: [{ model: Company, as: "company" }, { model: AssetCategory, as: "category" }, { model: Vendor, as: "vendor" }, { model: Location, as: "location" }, { model: Employee, as: "assignedEmployee" }], order: [["assetCode", "ASC"]] });
    const header = ["Company", "Asset Code", "Name", "Category", "Serial", "Status", "Condition", "Employee", "Location", "Purchase Price", "Current Value", "Useful Life", "Warranty Expiry"];
    const lines = [header.join(","), ...rows.map((a: any) => [a.company?.name, a.assetCode, a.name, a.category?.name, a.serialNumber, a.status, a.condition, a.assignedEmployee ? `${a.assignedEmployee.employeeCode} - ${a.assignedEmployee.name}` : "", a.location?.name, a.purchasePrice, a.currentValue, `${a.usefulLifeYears} years`, a.warrantyExpiry].map(csvEscape).join(","))];
    res.setHeader("Content-Type", "text/csv");
    res.setHeader("Content-Disposition", "attachment; filename=assetflow-assets.csv");
    res.send(lines.join("\n"));
  }
  catch (e) {
    next(e);
  }
});

exportRoutes.get("/assets.pdf", async (_req, res, next) => {
  try {
    const rows: any[] = await Asset.findAll({ include: [{ model: Company, as: "company" }, { model: AssetCategory, as: "category" }, { model: Vendor, as: "vendor" }, { model: Location, as: "location" }, { model: Employee, as: "assignedEmployee" }], order: [["assetCode", "ASC"]] });
    sendHtml(res, "assetflow-assets-report.html", reportHtml("Asset Inventory Report", ["Company", "Asset Code", "Name", "Category", "Serial", "Status", "Condition", "Employee", "Location", "Purchase", "Current", "Useful Life", "Warranty"], rows.map((a: any) => [a.company?.name, a.assetCode, a.name, a.category?.name, a.serialNumber, a.status, a.condition, a.assignedEmployee ? `${a.assignedEmployee.employeeCode} - ${a.assignedEmployee.name}` : "-", a.location?.name, a.purchasePrice, a.currentValue, `${a.usefulLifeYears} years`, a.warrantyExpiry]), `Total assets: <b>${rows.length}</b>`));
  }
  catch (e) {
    next(e);
  }
});

exportRoutes.get("/employees.pdf", async (_req, res, next) => {
  try {
    const rows: any[] = await Employee.findAll({ include: [{ model: Company, as: "companies" }, Location], order: [["employeeCode", "ASC"]] });
    sendHtml(res, "assetflow-employees-report.html", reportHtml("Employee List Report", ["Employee ID", "Name", "Companies", "Email", "Phone", "Designation", "Location", "Status", "Clearance"], rows.map((e: any) => [e.employeeCode, e.name, (e.companies || []).map((c: any) => c.code || c.name).join(", "), e.email, e.phone, e.designation, e.Location?.name, e.status, e.clearanceStatus]), `Total employees: <b>${rows.length}</b>`));
  }
  catch (e) {
    next(e);
  }
});

exportRoutes.get("/vendors.pdf", async (_req, res, next) => {
  try {
    const rows: any[] = await Vendor.findAll({ include: [{ model: Company, as: "company" }], order: [["name", "ASC"]] });
    sendHtml(res, "assetflow-vendors-report.html", reportHtml("Vendor List Report", ["Company", "Vendor", "Contact", "Phone", "Email", "Address", "Status"], rows.map((v: any) => [v.company?.name, v.name, v.contactPerson, v.phone, v.email, v.address, v.status]), `Total vendors: <b>${rows.length}</b>`));
  }
  catch (e) {
    next(e);
  }
});

exportRoutes.get("/purchases.pdf", async (_req, res, next) => {
  try {
    const rows: any[] = await Purchase.findAll({ include: [{ model: Company, as: "company" }, Vendor], order: [["purchaseDate", "DESC"]] });
    sendHtml(res, "assetflow-purchases-report.html", reportHtml("Purchase List Report", ["Company", "Invoice", "Vendor", "Purchase Date", "Total Amount", "Payment Status"], rows.map((p: any) => [p.company?.name, p.invoiceNumber, p.Vendor?.name, p.purchaseDate, p.totalAmount, p.paymentStatus]), `Total purchases: <b>${rows.length}</b>`));
  }
  catch (e) {
    next(e);
  }
});

exportRoutes.get("/assignments.pdf", async (_req, res, next) => {
  try {
    const rows: any[] = await AssetAssignment.findAll({ include: [{ model: Asset, include: [{ model: Company, as: "company" }] }, Employee], order: [["assignedAt", "DESC"]] });
    sendHtml(res, "assetflow-assignments-report.html", reportHtml("Assignment List Report", ["Company", "Asset Code", "Asset", "Employee", "Assigned At", "Condition", "Returned"], rows.map((x: any) => [x.Asset?.company?.name, x.Asset?.assetCode, x.Asset?.name, x.Employee ? `${x.Employee.employeeCode} - ${x.Employee.name}` : "-", x.assignedAt, x.conditionAtAssign, x.returnedAt ? "Yes" : "No"]), `Total assignments: <b>${rows.length}</b>`));
  }
  catch (e) {
    next(e);
  }
});

exportRoutes.get("/returns.pdf", async (_req, res, next) => {
  try {
    const rows: any[] = await AssetReturn.findAll({ include: [{ model: Asset, include: [{ model: Company, as: "company" }] }, Employee], order: [["createdAt", "DESC"]] });
    sendHtml(res, "assetflow-returns-report.html", reportHtml("Return & Clearance List Report", ["Company", "Asset Code", "Asset", "Employee", "Status", "Condition", "Penalty", "Notes"], rows.map((x: any) => [x.Asset?.company?.name, x.Asset?.assetCode, x.Asset?.name, x.Employee ? `${x.Employee.employeeCode} - ${x.Employee.name}` : "-", x.returnStatus, x.returnCondition, x.penaltyAmount, x.notes]), `Total returns: <b>${rows.length}</b>`));
  }
  catch (e) {
    next(e);
  }
});

exportRoutes.get("/repairs.pdf", async (_req, res, next) => {
  try {
    const rows: any[] = await RepairTicket.findAll({ include: [{ model: Asset, include: [{ model: Company, as: "company" }] }, Vendor], order: [["reportedAt", "DESC"]] });
    sendHtml(res, "assetflow-repairs-report.html", reportHtml("Repair & Upgrade List Report", ["Company", "Ticket", "Asset Code", "Asset", "Problem / Upgrade", "Vendor", "Cost", "Status", "Reported"], rows.map((x: any) => [x.Asset?.company?.name, x.ticketCode, x.Asset?.assetCode, x.Asset?.name, x.problem, x.Vendor?.name, x.repairCost, x.status, x.reportedAt]), `Total repair tickets: <b>${rows.length}</b>`));
  }
  catch (e) {
    next(e);
  }
});

exportRoutes.get("/finance.pdf", async (_req, res, next) => {
  try {
    const rows: any[] = await Asset.findAll({ include: [{ model: Company, as: "company" }, { model: AssetCategory, as: "category" }, { model: Employee, as: "assignedEmployee" }], order: [["purchaseDate", "ASC"]] });
    const totalPurchase = rows.reduce((s, a) => s + Number(a.purchasePrice || 0), 0);
    const totalCurrent = rows.reduce((s, a) => s + Number(a.currentValue || 0), 0);
    sendHtml(res, "assetflow-finance-report.html", reportHtml("Depreciation & Finance Report", ["Company", "Asset Code", "Asset", "Employee", "Purchase Date", "Purchase Value", "Current Value", "Depreciation", "Useful Life", "Method", "Warranty"], rows.map((a: any) => [a.company?.name, a.assetCode, a.name, a.assignedEmployee ? `${a.assignedEmployee.employeeCode} - ${a.assignedEmployee.name}` : "-", a.purchaseDate, a.purchasePrice, a.currentValue, Number(a.purchasePrice || 0) - Number(a.currentValue || 0), `${a.usefulLifeYears} years`, a.depreciationMethod, a.warrantyExpiry]), `Total purchase value: <b>${totalPurchase}</b> &nbsp; Current book value: <b>${totalCurrent}</b> &nbsp; Accumulated depreciation: <b>${totalPurchase - totalCurrent}</b>`));
  }
  catch (e) {
    next(e);
  }
});

exportRoutes.get("/audit-logs.csv", async (_req, res, next) => {
  try {
    const rows = await AuditLog.findAll({ order: [["createdAt", "DESC"]], limit: 500 });
    const lines = [["Date", "User", "Action", "Module", "Record"].join(","), ...rows.map((r: any) => [r.createdAt, r.userName, r.action, r.module, r.recordId].map(csvEscape).join(","))];
    res.setHeader("Content-Type", "text/csv");
    res.setHeader("Content-Disposition", "attachment; filename=assetflow-audit-logs.csv");
    res.send(lines.join("\n"));
  }
  catch (e) {
    next(e);
  }
});
